### ISSUE TITLE
question: how to use run_picus with sr1cs

### ISSUE THREAD

**Issue by ivokub** [Veridise/picus_gnark#1]
Hi, I'm gnark contributor and was interested in studying the tool. I'm not understanding how to run Picus though. It seems this repository outputs files in `sr1cs` extension, but Picus only accepts `circom` or `r1cs` (https://github.com/Veridise/Picus/blob/09dd87c292e92093fc685da046659eea176ae46f/picus.rkt#L44).

When I'm running the latest run_picus in Docker container, then I'm not seeing any output:
```bash
root@bcfa55008c4d:/Picus# ./run-picus /gnark-circuits/circuitMy.sr1cs 
root@bcfa55008c4d:/Picus# 
```

**Comment by sorawee** [comment]
Hi Ivo,

Thank you for your interest in Picus! While we have the Gnark support for our internal version of Picus, we think it isn’t ready for release to the public yet.

Feel free to contact us (sorawee@veridise.com) with the sr1cs and the source Go files, however, and we would be happy to run the tool for you.

Best,
Sorawee

**Comment by ivokub** [comment]
Thanks. I'll wait for the public release. We're rather interested in checking different parts of the gnark's standard library and would be time-consuming with sending back and forth. We're also not in a rush with it, just interested generally and can wait.
